### ISSUE TITLE
SIS upload script error "A JSON text must at least contain two octets!"

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/canvas#57]
Occasionally the sis_upload script throw this error:

/usr/local/ctools/app/ctupload/.rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
        from /usr/local/ctools/app/ctupload/.rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `new'
        from /usr/local/ctools/app/ctupload/.rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
        from /usr/local/ctools/app/ctupload/bin/sis_upload.rb:19:in `rescue in Canvas_API_GET'
        from /usr/local/ctools/app/ctupload/bin/sis_upload.rb:12:in `Canvas_API_GET'
        from /usr/local/ctools/app/ctupload/bin/sis_upload.rb:88:in `upload_to_canvas'
        from /usr/local/ctools/app/ctupload/bin/sis_upload.rb:358:in `<main>'
make: *** [canvastestupload] Error 1

It is due to the text being parsed is null or empty.

**Comment by zqian** [comment]
code fixes merged in after code reviews.
